// Dummy job data (replace with API data)
export const dummyJobs = [
    {
        id: 1,
        title: 'Frontend Developer',
        category: 'IT',
        postedAt: '2025-05-27',
        description: 'React Developer with 2+ years experience.',
    },
    {
        id: 2,
        title: 'Backend Engineer',
        category: 'IT',
        postedAt: '2025-05-24',
        description: 'Node.js, MongoDB knowledge required.',
    },
    {
        id: 3,
        title: 'Digital Marketing Specialist',
        category: 'Marketing',
        postedAt: '2025-05-21',
        description: 'SEO, Social Media Management expertise.',
    },
    {
        id: 4,
        title: 'Math Teacher',
        category: 'Education',
        postedAt: '2025-05-20',
        description: 'Experienced math teacher for high school.',
    },
    {
        id: 5,
        title: 'Graphic Designer',
        category: 'IT',
        postedAt: '2025-05-18',
        description: 'Adobe Photoshop, Illustrator expert.',
    },
    {
        id: 6,
        title: 'Content Writer',
        category: 'Marketing',
        postedAt: '2025-05-27',
        description: 'Write engaging blogs and articles.',
    },
    {
        id: 7,
        title: 'Physics Lecturer',
        category: 'Education',
        postedAt: '2025-05-23',
        description: 'University level physics teaching job.',
    },
    {
        id: 8,
        title: 'HR Manager',
        category: 'Marketing',
        postedAt: '2025-05-22',
        description: 'Manage recruitment and employee relations.',
    },
    {
        id: 9,
        title: 'UI/UX Designer',
        category: 'IT',
        postedAt: '2025-05-19',
        description: 'Design modern web and mobile interfaces.',
    },
    {
        id: 10,
        title: 'Video Editor',
        category: 'Marketing',
        postedAt: '2025-05-25',
        description: 'Edit promotional and YouTube videos.',
    },
    {
        id: 11,
        title: 'Biology Teacher',
        category: 'Education',
        postedAt: '2025-05-26',
        description: 'Science teacher needed for class 9-10.',
    },
    {
        id: 12,
        title: 'Full Stack Developer',
        category: 'IT',
        postedAt: '2025-05-20',
        description: 'React, Node.js, and database knowledge.',
    },
    {
        id: 13,
        title: 'Brand Manager',
        category: 'Marketing',
        postedAt: '2025-05-17',
        description: 'Develop and maintain brand strategy.',
    },
    {
        id: 14,
        title: 'English Teacher',
        category: 'Education',
        postedAt: '2025-05-27',
        description: 'Fluent English teacher for school level.',
    },
    {
        id: 15,
        title: 'IT Support Technician',
        category: 'IT',
        postedAt: '2025-05-26',
        description: 'Solve tech issues in office environment.',
    },
];