import Sidebar from '@/components/dashboard/Sidebar'
import "@/app/globals.css"
import React from 'react'
import DashboardHeader from '@/components/dashboard/Header';
import DashboardState from '@/contextApi/DashboardState';
import { Toaster } from '@/components/ui/toaster';


export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
    return (

        <html lang="en">
            <body cz-shortcut-listen="true">

                <Toaster />
                <div className='flex'>
                    <DashboardState>
                        <Sidebar />
                        <main className=' w-full md:flex-1 h-screen bg-gray-200 overflow-y-auto'>
                            <DashboardHeader />
                            <div className='p-3'>
                                {children}
                                <div className=' my-5' />
                            </div>
                        </main>
                    </DashboardState>
                </div>
            </body>
        </html>
    )
}
